### ISSUE TITLE
No displayed between word tags

### ISSUE THREAD

**Issue by sonofmun** [Capitains/flask-capitains-nemo#105]
Take a look at this text: http://cts.perseids.org/read/greekLit/tlg0031/tlg002/INTF-grc1/1.1-1.20
Notice that several of the words run together. These words are in individual word tags with spaces between the word tags. What is the best way to deal with this problem? Spaces between `<w>` tags?

**Comment by PonteIneptique** [comment]
Space between `w` but also and more importantly potentially change your XSL...
