### ISSUE TITLE
heroku deployment documentation

### ISSUE THREAD

**Issue by balmas** [Capitains/flask-capitains-nemo#14]
If we're going to recommend deployment on heroku, we might want to document some things

to run locally, you need to install these packages:

python-dev
libxml2-dev
libxslt-dev

gunicorn is probably not such a great idea for large CTS repos, as it seems fixed at a 30ms timeout. Waitress works a little better (see http://blog.etianen.com/blog/2014/01/19/gunicorn-heroku-django/)

**Comment by PonteIneptique** [comment]
Done in the tutorial . 
Damn.
That was an issue I did not expect to close.
