### ISSUE TITLE
allow callbacks, wildcards, and and regexes in chunker dictionary keys

### ISSUE THREAD

**Issue by balmas** [Capitains/flask-capitains-nemo#2]
I think it would be really useful if we could also allow callbacks, wildcards and regexes in chunker dictionary keys. For a large corpus, having to specify each chunk-scheme override at the version level might be a bit cumbersome.

**Comment by PonteIneptique** [comment]
While I agree, the cost of the development of something like that is... High. Through, there is no reason not to use regex or wildards in the default. Default is its own function, which means that you can use a regexp on whatever informations you have access to. I think the version stuff is exactly to avoid this situation where you put in default a one if line.

Happy to hear what you think about my answer. And not sure to understand the sentence, typo ?

**Comment by balmas** [comment]
I might be misunderstanding the code, but I'm not sure I agree that this the cost of development is high.

I'm looking at these lines:

https://github.com/Capitains/flask-capitains-nemo/blob/master/flask_nemo.py#L657-L659

    if str(text.urn) in self.chunker:
            return self.chunker[str(text.urn)](text, reffs)
    return self.chunker["default"](text, reffs)

Couldn't we do something like this (pseudocode):

      for key in self.chunker
         # if key is function name call it on the urn and if returns true, then call chunker
         # otherwise just check if key matches urn
         if (isFunction(key) && key.call(str(text.urn))) || str(text.urn) =~ /key/
             return self.chunker[str(text.urn)](text, reffs)
         else
             return self.chunker["default"](text, reffs)

**Comment by PonteIneptique** [comment]
Closed by #3
