### ISSUE TITLE
Add textgroup model object to the texts view

### ISSUE THREAD

**Issue by balmas** [Capitains/flask-capitains-nemo#27]
Need to be able to access texgroup metadata from the texts view

**Comment by PonteIneptique** [comment]
I am not sure this one has been fixed but I'd like to have you get a look. I am not sure what it implied back in the time. I'd be happy to see it fixed before we dive in 1.0.0 @balmas

**Comment by balmas** [comment]
I'm not sure, but I think this was needed in order to be able to put the textgroup into the breadcrumb path in the Texts view.

Currently, the breadcrumb is missing that level, and displays the first work rather than the textgroup
