### ISSUE TITLE
Add a GetPrevNext which reuse GetValidReff grouper

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/flask-capitains-nemo#32]

**Comment by balmas** [comment]
This is why navigation on e.g. urn:cts:latinLit:phi0959.phi001.perseus-eng2 jumps poems (so that you get part of a poem when using next/prev) right?

**Comment by PonteIneptique** [comment]
Exactly. I need to implement this more clever system to GetPrevNext :')
