### ISSUE TITLE
need to be able to pull in secondary css via command-line script

### ISSUE THREAD

**Issue by balmas** [Capitains/flask-capitains-nemo#35]
I'm not positive of the best way to pull in a secondary css file when running from the command line. I know I can make it an argument, but how to get it to serve the files from examples?  Should the tei.pb.min.css maybe be available in the main nemo package so that it can be used from there? But I'm not sure how to get the secondary path to point there...

We do need this because without the tei.pb.min.css the display isn't so useful

**Comment by PonteIneptique** [comment]
Fixed in #37
