### ISSUE TITLE
add OAuth client functionality

### ISSUE THREAD

**Issue by balmas** [Capitains/flask-capitains-nemo#66]
We want to be able to authenticate users with Perseids or other OAUTH2 providers.

**Comment by balmas** [comment]
may use RAUTH lib for this https://rauth.readthedocs.io/en/latest/ or Flask-OAuthlib https://github.com/lepture/flask-oauthlib  (need to investigate which is best or if other better solutions exist)

**Comment by PonteIneptique** [comment]
I am totally against it... May we speak about it before you go further ? :)

**Comment by balmas** [comment]
Notes from our discussion:

1. if we we add this, is should be via a plugin
2. it could be that we need to do nothing more than adding an existing flask extension (such as noted above) to the driving app
3. Bridget to investigate the existing flask extensions and then report back

**Comment by balmas** [comment]
This work is taking place in a new plugin, https://github.com/Capitains/nemo-oauth-plugin.  I think we can probably close this issue now, and track remaining work on oauth there. @PonteIneptique do you agree?

**Comment by PonteIneptique** [comment]
Closed because of nemo oauth plugin
