### ISSUE TITLE
add customizable footer template to all pages (not just passage)

### ISSUE THREAD

**Issue by balmas** [Capitains/flask-capitains-nemo#68]
it would be nice if there was a customizable footer template for all default pages

**Comment by PonteIneptique** [comment]
If people need to customize the templates that much, they just'd be better creating a whole theme.

**Comment by balmas** [comment]
I agree that this should be customized in a theme, but I disagree that a theme should require customization of all parts. It should be possible to create a theme which only updates parts of the display, particularly things like headers and footers, without requiring customization of the entire container
