### ISSUE TITLE
Fix the non showing left menu bug

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/flask-capitains-nemo#9]
And find where it comes from !

**Comment by balmas** [comment]
@PonteIneptique I spent a little time look at this tonight. I think it is a problem with css caching or load order or both.  If the browser doesn't refresh all of the css when you load the page and instead serves it from the cache this is when the problem occurs.  If you force a refresh of the css from the server, the page displays properly.  

I don't think you're using less, and so it's probably not this issue: https://gist.github.com/attaboy/1346280 but I'm wondering if it's caused in some way by the inclusion of the secondary css files. 

There might also be a loading order issue at play, I'm not sure. I can never reproduce the problem running locally. The browser seems never to serve files from localhost from the cache (which is maybe controlled by some other http header in development mode).

Might also be something bootstrap-specific, in which case I wonder if using the flask-bootstrap extension would help.

**Comment by PonteIneptique** [comment]
it could be useful to see http://stackoverflow.com/questions/20646822/how-to-serve-static-files-in-flask

**Comment by PonteIneptique** [comment]
I think I just fixed it @balmas @517c132

**Comment by balmas** [comment]
Yay!

**Comment by PonteIneptique** [comment]
The bug is back. Something has probably overwritteen previous commit...

**Comment by PonteIneptique** [comment]
https://github.com/Capitains/flask-capitains-nemo/blob/master/flask_nemo/data/static/css/theme.min.css#L45

**Comment by PonteIneptique** [comment]
Actually, it was never merged...
